export const cartConstants = {
    CART_ADD_ITEM: "CART_ADD_ITEM",
    CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
    CART_INQTY_ITEM:"CART_INQTY_ITEM",
    CART_DEQTY_ITEM:"CART_DEQTY_ITEM",
    CART_REMOVE_ITEM:"CART_REMOVE_ITEM",
    CART_EMPTY_ITEM:"CART_EMPTY_ITEM"
  };